club_abbreviations:
  # from the GAOC HS list
  StoHS:  'Stockbridge HS'
  ELHS:   'Eagles Landing HS'
  LueHS:  'Luella HS'
  UGHS:   'Union Grove HS'
  PrkvHS: 'Parkview HS'
  PCHS:   'Peach County HS'
  JacHS:  'Jackson HS'
  ULHS:   'Upson-Lee HS'
  BruHS:  'Brunswick HS'
  GreHS:  'Greenbrier HS'
  WooHS:  'Woodstock HS'
  SCHS:   'Sandy Creek HS'
  WalHS:  'Walhalla HS'
  HarHS:  'Harrison HS'
  NCHS:   'North Cobb HS'
  KMHS:   'Kennesaw Mountain HS'
  CamHS:  'Campbell HS'
  CalCHS: 'Calhoun County HS'
  SMHS:   'Stone Mountain HS'
  CraCHS: 'Crawford County HS'
  CKHS:   'Cross Keys HS'
  FCHS:   'Franklin County HS'
  HCHS:   'Henry County HS'
  EtoHS:  'Etowah HS'
  LasHS:  'Lassiter HS'
  SwDHS:  'Southwest Dekalb HS'
  LCHS:   'Lee County HS'
  TPHS:   'Terry Parker HS'
  EHHS:   'East Hall HS'
  EWHS:   'Ed White HS'
  SEHS:   'South Effingham HS'
  JefCHS: 'Jefferson County HS'
  McEHS:  'McEachern HS'
  NeaHS:  'Nease HS'
  CofHS:  'Coffee HS'
  MCHS:   'Macon Co HS'
  CaiHS:  'Cairo HS'
  SteHS:  'Stephenson HS'
  LitHS:  'Lithonia HS'
  SAHS:   'South Aiken HS'
  BalHS:  'Baldwin HS'
  GaiHS:  'Gainesville HS'
  LauHS:  'Laurens HS'
  ColHS:  'Columbia HS'
  FMMA:   'Francis Marion Military Academy'
  PerHS:  'Perry HS'
  AllHS:  'Allatoona HS'
  DHHS:   'Druid Hills HS'
  SprHS:  'Sprayberry HS'
  ThoHs:  'Thomson HS'
  DulHS:  'Duluth HS'
  VetHS:  'Veterans HS'
  RosHS:  'Roswell HS'
  BroHS:  'Brookwood HS'
  CHHS:   'Chapel Hill HS'
  BFA:    'Ben Franklin Academy'
  FDHS:   'Ft Dorchester HS'
  EasHS:  'Easley HS'
  TLHHS:  'TL Hanna HS'
  CenHS:  'Central HS'
  WPHS:   'Winter Park HS'
  MLKHS:  'Martin Luther King HS'
  WesHS:  'Westside HS'
  CCHS:   'Cross Creek HS'
  FBHS:   'Fernandina Beach HS'
  DunHS:  'Dunedin HS'
  HHHS:   'Hilton Head HS'
  SumHS-SC: 'Summerville HS'
  TafHS:  'Taft HS'
  YorHS:  'York HS'
  HGHS:   'Hillgrove HS'
  NorHS:  'Northside HS (WR)'
  WRHS:   'Warner Robins HS'
  McDHS:  'McDowell HS'
  CamCHS: 'Camden County HS'
  RidHS:  'Ridgeview HS'
  HouCHS: 'Houston County HS'
  HerHS:  'Heritage HS'
# Appended to the GAOC HS list
  CGHS:   'Cedar Grove HS'
  ClayHS: "Clay HS"
  FirstCHS: "First Coast HS"
  BishopKHS: "Bishop Kenny HS"
  JohnsCHS: "Johns Creek HS"
  FlemingHS: "Fleming Island HS"
  MandarinHS: "Mandarin HS"
  OrangeParkHS: "Orange Park HS"
  RobertELeeHS: "Robert E Lee HS"
  PantherCreekHS: "Panther Creek HS"
  HVJenkinsHS: "HV Jenkins HS"
  Glynn: "Glynn Academy HS"
  Middleburg: "Middleburg HS"
  WrenHS: "Wren HS"
  MoutainView: "Mountain View HS"
  McDoHS: "McDonough HS"
  Robertsdale: "Robertsdale HS"
  Valdosta: "Valdosta HS"
  Sequoyah: "Sequoyah HS"
