defaults: &defaults
   title:         "Reentrant - news that's fit"
   admin_pwd:     <%= ENV["ADMIN_PWD"] || 'not_very_secret' %>
   season: "18/19"
   
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
