defaults: &defaults
   title:         "Reentrant - news that's fit"
   admin_pwd:     <%= ENV["ADMIN_PWD"] || 'not_very_secret' %>
   season: "19/20"
   min_races: 3
   top: 5
   
development:
  <<: *defaults

test:
  <<: *defaults
  min_races: 2

production:
  <<: *defaults
